name: aj_maintain
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.5.3
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.2.0
  random_string: ^2.3.1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  pdf: ^3.11.3
  printing: ^5.14.2
  blue_thermal_printer: ^1.2.3
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/icons/
flutter_icons:
  android: true
  image_path: "assets/icons/aj_logo.png"