// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9D_eRzLLLvqU4Hc8AZ3_pJffgxmUWG8',
    appId: '1:634155670048:android:99195581ec7da80f037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIu0zKODfPc6Xi2kKrWG9wW1-0m4OhvNI',
    appId: '1:634155670048:ios:05fa429af2d8f398037a45',
    messagingSenderId: '634155670048',
    projectId: 'my-flutter-app-2750c',
    storageBucket: 'my-flutter-app-2750c.firebasestorage.app',
    androidClientId: '634155670048-bt0jkb6elc883datq14dvlg2llma5tkd.apps.googleusercontent.com',
    iosClientId: '634155670048-q3ok805up4bn79dpni42qndkd4maibkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ajMaintain',
  );
}
